version: 2

sources:
  - name: raw
    database: HEALTHCARE_ANALYTICS_DB
    schema: RAW
    tables:
      - name: PATIENTS
      - name: DOCTORS
      - name: APPOINTMENTS
      - name: BILLING
